[global]
   workgroup = NEXORA
   security = ads
   realm = NEXORA.LOCAL
   netbios name = NEXORA-FS01
   
   server string = Nexora Central File Storage
   log file = /var/log/samba/log.%m
   max log size = 50
   
   # Kerberos config
   kerberos method = secrets and keytab
   dedicated keytab file = /etc/krb5.keytab
   
   # Shares
   [Public]
      path = /srv/shares/public
      read only = no
      guest ok = yes
      
   [Backups]
      path = /srv/shares/backups
      read only = no
      valid users = @NEXORA\svc_backup, @NEXORA\it.admin
      
   [Admin]
      path = /srv/shares/admin
      read only = yes
      valid users = it.admin
