"""Report generator — assembles session data into a structured Markdown report."""
from datetime import timezone
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from src.db.database import Session, Note, CommandLog, SiemEvent


async def generate_report(session: Session, db: AsyncSession) -> str:
    """Return a Markdown report string for the given session."""
    notes_result = await db.execute(
        select(Note).where(Note.session_id == session.id).order_by(Note.created_at)
    )
    notes = list(notes_result.scalars())

    siem_result = await db.execute(
        select(SiemEvent).where(SiemEvent.session_id == session.id).order_by(SiemEvent.created_at)
    )
    siem_events = list(siem_result.scalars())

    cmd_result = await db.execute(
        select(CommandLog).where(CommandLog.session_id == session.id).order_by(CommandLog.created_at)
    )
    commands = list(cmd_result.scalars())

    role_label = "Penetration Test" if session.role == "red" else "Incident Response"
    started = session.started_at.strftime("%Y-%m-%d %H:%M UTC")
    ended = session.completed_at.strftime("%Y-%m-%d %H:%M UTC") if session.completed_at else "In progress"

    sections = [
        f"# {role_label} Report — {session.scenario_id}",
        "",
        "## Engagement Details",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Scenario | {session.scenario_id} |",
        f"| Role | {session.role.upper()} |",
        f"| Methodology | {session.methodology.upper()} |",
        f"| Started | {started} |",
        f"| Completed | {ended} |",
        f"| Final Score | {session.score} / 100 |",
        f"| Hints used | {len(session.hints_used or [])} |",
        "",
    ]

    # Findings section (red team)
    findings = [n for n in notes if n.tag == "finding"]
    if findings:
        sections += ["## Findings", ""]
        for i, f in enumerate(findings, 1):
            sections += [f"### Finding {i}", f.content, ""]

    # Evidence
    evidence = [n for n in notes if n.tag == "evidence"]
    if evidence:
        sections += ["## Evidence", ""]
        for e in evidence:
            sections += [f"- {e.content}"]
        sections += [""]

    # IOCs (blue team)
    iocs = [n for n in notes if n.tag == "ioc"]
    if iocs:
        sections += ["## Indicators of Compromise", ""]
        for ioc in iocs:
            sections += [f"- `{ioc.content}`"]
        sections += [""]

    # SIEM timeline (blue team)
    critical_high = [e for e in siem_events if e.severity in ("CRITICAL", "HIGH")]
    if critical_high:
        sections += ["## Attack Timeline (HIGH/CRITICAL events)", ""]
        for ev in critical_high[:20]:
            ts = ev.created_at.strftime("%H:%M:%S")
            mitre = f" [{ev.mitre_technique}]" if ev.mitre_technique else ""
            sections += [f"- `{ts}` **{ev.severity}**{mitre} — {ev.message}"]
        sections += [""]

    # Recommendations
    remediations = [n for n in notes if n.tag == "remediation"]
    if remediations:
        sections += ["## Recommendations", ""]
        for r in remediations:
            sections += [f"- {r.content}"]
        sections += [""]

    # General notes
    general = [n for n in notes if n.tag == "note"]
    if general:
        sections += ["## Notes", ""]
        for g in general:
            sections += [f"{g.content}", ""]

    sections += [
        "---",
        "_Generated by CyberSim — educational use only._",
    ]

    return "\n".join(sections)
