listen=YES
listen_ipv6=NO
anonymous_enable=YES
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
chroot_local_user=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
ssl_enable=NO
pasv_enable=YES
pasv_min_port=10000
pasv_max_port=10100
anon_root=/var/www/html/uploads
allow_writeable_chroot=YES
background=NO
ftpd_banner=Welcome to NovaMed FTP Archive.
